### ISSUE TITLE
Ciphertext randomness

### ISSUE THREAD

**Issue by karliwson** [andrivet/ADVobfuscator#14]
Congratulations for your great work. I've been testing it, but I have one doubt:

I see that you use a `char` as key for `MetaString`. Does this mean that there will be only **255** possible "ciphertexts" for a given plaintext (using the same algorythm)?

**Comment by andrivet** [comment]
It depends of the algorithm. For example with XOR, the only way to make a XOR of a byte with another value is to also use a byte, so you have 255 (256 - 1 because 0 is not allowed) possibilities. This is obfuscation, not encryption. But if you are using other algorithms, it can be different. My code shows the principles of what is possible. It is up to you to make new algorithms.
