### ISSUE TITLE
Can you show me how to use it please ? 

### ISSUE THREAD

**Issue by Dj-jom2x** [andrivet/ADVobfuscator#2]
Can you show me how to use it please ? 

i want to see it obfuscate an c++ output then if i look in ida 6.8 i must see the string has been obfuscate :( please

**Comment by andrivet** [comment]
What exactly is your problem? On which platform, which compiler, which command line, etc.

**Comment by Dj-jom2x** [comment]
hmm i created some dll and i want to obfuscate this to make it unreadable inside ida 6.8 and olldbg is this the right project that im looking for ? sorry for this stupid question :)

**Comment by andrivet** [comment]
Since you are mentioning "DLL" I assume that you are under Windows. There is an example of code for Visual Studio 2015 in the repository. You can look at it as a reference. There is also a white paper that describes precisely what ADVobfuscator is, how it works, etc. If you are looking for a general-purpose obfuscator, as for as I know, there are some for Microsoft C/C++ compilers but they are all commercial.
